"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.ApiClientNavigationMetadata = exports.ApiClientUriTemplate = exports.createApiClient = void 0;
/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
const pets_1 = require("./pets/");
// @ts-ignore
const kiota_abstractions_1 = require("@microsoft/kiota-abstractions");
// @ts-ignore
const kiota_serialization_form_1 = require("@microsoft/kiota-serialization-form");
// @ts-ignore
const kiota_serialization_json_1 = require("@microsoft/kiota-serialization-json");
// @ts-ignore
const kiota_serialization_multipart_1 = require("@microsoft/kiota-serialization-multipart");
// @ts-ignore
const kiota_serialization_text_1 = require("@microsoft/kiota-serialization-text");
/**
 * Instantiates a new {@link ApiClient} and sets the default values.
 * @param requestAdapter The request adapter to use to execute the requests.
 */
function createApiClient(requestAdapter) {
    (0, kiota_abstractions_1.registerDefaultSerializer)(kiota_serialization_form_1.FormSerializationWriterFactory);
    (0, kiota_abstractions_1.registerDefaultSerializer)(kiota_serialization_json_1.JsonSerializationWriterFactory);
    (0, kiota_abstractions_1.registerDefaultSerializer)(kiota_serialization_text_1.TextSerializationWriterFactory);
    (0, kiota_abstractions_1.registerDefaultSerializer)(kiota_serialization_multipart_1.MultipartSerializationWriterFactory);
    (0, kiota_abstractions_1.registerDefaultDeserializer)(kiota_serialization_form_1.FormParseNodeFactory);
    (0, kiota_abstractions_1.registerDefaultDeserializer)(kiota_serialization_json_1.JsonParseNodeFactory);
    (0, kiota_abstractions_1.registerDefaultDeserializer)(kiota_serialization_text_1.TextParseNodeFactory);
    if (requestAdapter.baseUrl === undefined || requestAdapter.baseUrl === "") {
        requestAdapter.baseUrl = "https://{region}.foo.com";
    }
    const pathParameters = {
        "baseurl": requestAdapter.baseUrl,
    };
    return (0, kiota_abstractions_1.apiClientProxifier)(requestAdapter, pathParameters, exports.ApiClientNavigationMetadata, undefined);
}
exports.createApiClient = createApiClient;
/**
 * Uri template for the request builder.
 */
exports.ApiClientUriTemplate = "{+baseurl}";
/**
 * Metadata for all the navigation properties in the request builder.
 */
exports.ApiClientNavigationMetadata = {
    pets: {
        requestsMetadata: pets_1.PetsRequestBuilderRequestsMetadata,
        navigationMetadata: pets_1.PetsRequestBuilderNavigationMetadata,
    },
};
/* tslint:enable */
/* eslint-enable */
