/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { createPetFromDiscriminatorValue, type Pet } from '../../models/';
// @ts-ignore
import { ToysRequestBuilderRequestsMetadata, type ToysRequestBuilder } from './toys/';
// @ts-ignore
import { type BaseRequestBuilder, type KeysToExcludeForNavigationMetadata, type NavigationMetadata, type Parsable, type ParsableFactory, type RequestConfiguration, type RequestInformation, type RequestsMetadata } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /pets/{petId}
 */
export interface WithPetItemRequestBuilder extends BaseRequestBuilder<WithPetItemRequestBuilder> {
    /**
     * The toys property
     */
    get toys(): ToysRequestBuilder;
    /**
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {Promise<Pet>}
     */
     get(requestConfiguration?: RequestConfiguration<object> | undefined) : Promise<Pet | undefined>;
    /**
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {RequestInformation}
     */
     toGetRequestInformation(requestConfiguration?: RequestConfiguration<object> | undefined) : RequestInformation;
}
/**
 * Uri template for the request builder.
 */
export const WithPetItemRequestBuilderUriTemplate = "{+baseurl}/pets/{petId}";
/**
 * Metadata for all the navigation properties in the request builder.
 */
export const WithPetItemRequestBuilderNavigationMetadata: Record<Exclude<keyof WithPetItemRequestBuilder, KeysToExcludeForNavigationMetadata>, NavigationMetadata> = {
    toys: {
        requestsMetadata: ToysRequestBuilderRequestsMetadata,
    },
};
/**
 * Metadata for all the requests in the request builder.
 */
export const WithPetItemRequestBuilderRequestsMetadata: RequestsMetadata = {
    get: {
        uriTemplate: WithPetItemRequestBuilderUriTemplate,
        responseBodyContentType: "application/json",
        adapterMethodName: "send",
        responseBodyFactory:  createPetFromDiscriminatorValue,
    },
};
/* tslint:enable */
/* eslint-enable */
