"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.PetsRequestBuilderRequestsMetadata = exports.PetsRequestBuilderNavigationMetadata = exports.PetsRequestBuilderUriTemplate = void 0;
/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
const models_1 = require("../models/");
// @ts-ignore
const errorEscaped_1 = require("./errorEscaped/");
// @ts-ignore
const item_1 = require("./item/");
// @ts-ignore
const kiota_abstractions_1 = require("@microsoft/kiota-abstractions");
/**
 * Uri template for the request builder.
 */
exports.PetsRequestBuilderUriTemplate = "{+baseurl}/pets?skip={skip}&top={top}";
/**
 * Metadata for all the navigation properties in the request builder.
 */
exports.PetsRequestBuilderNavigationMetadata = {
    byPetId: {
        requestsMetadata: item_1.WithPetItemRequestBuilderRequestsMetadata,
        navigationMetadata: item_1.WithPetItemRequestBuilderNavigationMetadata,
        pathParametersMappings: ["petId"],
    },
    errorEscaped: {
        requestsMetadata: errorEscaped_1.ErrorRequestBuilderRequestsMetadata,
    },
};
/**
 * Metadata for all the requests in the request builder.
 */
exports.PetsRequestBuilderRequestsMetadata = {
    get: {
        uriTemplate: exports.PetsRequestBuilderUriTemplate,
        responseBodyContentType: "application/json",
        adapterMethodName: "send",
        responseBodyFactory: kiota_abstractions_1.createUntypedNodeFromDiscriminatorValue,
    },
    post: {
        uriTemplate: exports.PetsRequestBuilderUriTemplate,
        adapterMethodName: "sendNoResponseContent",
        requestBodyContentType: "application/json",
        requestBodySerializer: models_1.serializePet,
        requestInformationContentSetMethod: "setContentFromParsable",
    },
};
/* tslint:enable */
/* eslint-enable */
