/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { createPetFromDiscriminatorValue, type Pet } from '../../../models/';
// @ts-ignore
import { type BaseRequestBuilder, type Parsable, type ParsableFactory, type RequestConfiguration, type RequestInformation, type RequestsMetadata } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /pets/{petId}/toys
 */
export interface ToysRequestBuilder extends BaseRequestBuilder<ToysRequestBuilder> {
    /**
     * Get a Pet list.
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {Promise<Pet>}
     */
     get(requestConfiguration?: RequestConfiguration<object> | undefined) : Promise<Pet | undefined>;
    /**
     * Get a Pet list.
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {RequestInformation}
     */
     toGetRequestInformation(requestConfiguration?: RequestConfiguration<object> | undefined) : RequestInformation;
}
/**
 * Uri template for the request builder.
 */
export const ToysRequestBuilderUriTemplate = "{+baseurl}/pets/{petId}/toys";
/**
 * Metadata for all the requests in the request builder.
 */
export const ToysRequestBuilderRequestsMetadata: RequestsMetadata = {
    get: {
        uriTemplate: ToysRequestBuilderUriTemplate,
        responseBodyContentType: "application/json",
        adapterMethodName: "send",
        responseBodyFactory:  createPetFromDiscriminatorValue,
    },
};
/* tslint:enable */
/* eslint-enable */
